### PR TITLE
Zh/email subscription

### PR DESCRIPTION
**Pull request by zkhussain**
This PR allows a user to subscribe to get email updates. The account management page has also been updated according to the design. Please let me know if I should make any changes.

Account Management Page:
account-management

Email Subscription and Unsubscribe Page (this page's link is attached below all emails we send in case the user wants to unsubscribe):
email-subscription

### CODE REVIEW

**Comment by Cliftonz** [comment]
I think we should remove the termination date, people could take that the wrong way.

Lastly, a user should be set to subscribe when their user is created.

**Comment by Cliftonz** [comment]
Otherwise looks good

**Comment by zkhussain** [comment]
Agree, we can also replace that with "Account active until" or should I just remove it?

**Comment by zkhussain** [comment]
Updated to have icons as Jason suggested:
image

The admin panel is also updated to have icons:
image

**Comment by Cliftonz** [comment]
looks great

**Review by Cliftonz — APPROVED** [review]

**Review by jasekiw — APPROVED** [review]

**Pull request merged**
