### PR TITLE
Ze/503 page updates

### PR DESCRIPTION
**Pull request by WarriorAchilles**
Updated the 503 page to correctly display maintenance information based on changes made in backend.
503-updates

### CODE REVIEW

**Comment by Cliftonz** [comment]
@WarriorAchilles  Can you please add a gif of the change?

**Comment by Cliftonz** [comment]
@WarriorAchilles 
It looks good overall.
 can you add some styling flare to the "service unavailable" 

Can you make the 503 smaller and make it a secondary color like grey.

Lastly you have both a maintenance description and a down description on the page instead of being up in there own situation.

After you make these changes can you update the PR to include:
- you using the app and killing the backend to have the 503 pop up with the down message
- you using the app and a maintenance window starts to have the 503 pop-up

This should cover the use cases we want to see for this feature on the front end

^ _**DISREGUARD**_

**Comment by WarriorAchilles** [comment]
If there is maintenance info in the database, the page will show this:
maintenance
if there is no maintenance info, it will show this:
default

**Review by Cliftonz — APPROVED** [review]
Lgtm

**Comment by jasekiw** [comment]
@WarriorAchilles 

Can you use luxon to parse the utc timestamp and display it in a human readable timestamp in the browser's timezone?


Also, this may have already been discussed but do we have the license to use that image? Where did you find it? Can you link the image and license here?

**Comment by WarriorAchilles** [comment]
> @WarriorAchilles
> 
> Can you use luxon to parse the utc timestamp and display it in a human readable timestamp in the browser's timezone?
> 
> Also, this may have already been discussed but do we have the license to use that image? Where did you find it? Can you link the image and license here?

@jasekiw 
The image is an adobe stock image obtained with an education license. Here are links to the image on adobe stock (it's a collection of images so I cropped to the one I wanted) as well as to the details of the education license:
https://stock.adobe.com/images/young-male-sysadmin-set-collection-of-man-working/284808949?prev_url=detail
https://stock.adobe.com/enterprise-conditions#educationLicenses

I'll get to work on displaying the timestamp better

**Comment by WarriorAchilles** [comment]
If the current date is not the date that the site is scheduled to be back up, this is what the page will display:
up at date

If the current date is the date that it is scheduled to be back up, then the page will just display the scheduled time:
up at time

**Comment by Cliftonz** [comment]
@WarriorAchilles the last sentence should be, '...please contact your local administrator'.

Other then that looks good.

**Review by jasekiw — APPROVED** [review]

**Pull request merged**
